version: "3.8"
name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_VAR_PIHOLE: $HOMEPAGE_VAR_PIHOLE
      HOMEPAGE_VAR_PLEX: $HOMEPAGE_VAR_PLEX
      HOMEPAGE_VAR_PORTAINER: $HOMEPAGE_VAR_PORTAINER
      HOMEPAGE_VAR_NPM_USERNAME: $HOMEPAGE_VAR_NPM_USERNAME
      HOMEPAGE_VAR_NPM_PASSWORD: $HOMEPAGE_VAR_NPM_PASSWORD
      

