version: '3.8'
name: nginx
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    image: my-nginx
    restart: unless-stopped
    ports:
      - '8090:8080'
    volumes:
      - ./static:/app/static
