title: Florin's HomeLAB
background: 
  image: /images/background.webp
  opacity: 35

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Network Services:
    style: row
    columns: 3

  Media Services:
    style: column
  Applications:
    style: column
  Information:
    style: column

  Developer:
    style: row
    columns: 4