title: Florin's HomeLAB
background: 
  image: /images/background.webp
  opacity: 35

useEqualHeights: true
disableCollapse: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Network Services:
    style: row
    columns: 3

  Applications:
    style: row
    columns: 3

  Media Services:
    style: column

  Information:
    style: column

  Developer:
    style: row
    columns: 4