- search:
    provider: google
    target: _blank

- glances:
    url: https://glances.home.stancu.me
    label: Intel NUC
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk:
        - /root
        - /backup
    expanded: false